remote_theme: jekyll/minima

yt_base: https://yt.werkgymnasium.eu

github_repo: tna76874/collection_sources

markdown: null

collections:
  sources:
    output: true

exclude:
  - docker-compose.yml
  - README.md
  - manage.py

gems:
  - jekyll